{{- range $k, $v := .Values.origins }}
  {{- $appname := $k | splitList "." | first | trunc 40 | trimSuffix "-" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: xrootd-{{ $appname }}
  name: xrootd-{{ $appname }}
  namespace: {{ $.Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: xrootd-{{ $appname }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: '8000'
        prometheus.io/scrape: 'true'
        k8s.v1.cni.cncf.io/networks: '{{ $v.network | toJson }}'
      labels:
        io.kompose.service: xrootd-{{ $appname }}
    spec:
      containers:
      - env:
        {{- if $.Values.env }}
        {{- toYaml $.Values.env | nindent 8 }}
        {{- end }}
        {{- if $v.env }}
        {{- toYaml $v.env | nindent 8 }}
        {{- end }}
        image: {{ ($v.image) | default $.Values.default_params.image | toJson }}
        imagePullPolicy: {{ ($v.imagePullPolicy) | default $.Values.default_params.imagePullPolicy | toJson }}
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - 'mkdir -p /etc/grid-security/xrootd/; cp /etc/grid-security/xrootd*.pem
                /etc/grid-security/xrootd/; chown -R xrootd:xrootd /etc/grid-security/xrootd/;
                cp /tmp/macaroon-secret /etc/xrootd/macaroon-secret; chown xrootd:xrootd
                /etc/xrootd/macaroon-secret;
                '
        name: xrootd-{{ $appname }}
        resources:
          limits:
            cpu: {{ (($v.resources).limits).cpu | default $.Values.default_params.resources.limits.cpu | toJson }}
            memory: {{ (($v.resources).limits).memory | default $.Values.default_params.resources.limits.memory | toJson }}
          requests:
            cpu: {{ (($v.resources).requests).cpu | default $.Values.default_params.resources.requests.cpu | toJson }}
            memory: {{ (($v.resources).requests).memory | default $.Values.default_params.resources.requests.memory | toJson }}
        securityContext:
          capabilities:
            add:
            - CAP_SETUID
            - CAP_SETGID
            - CAP_DAC_OVERRIDE
        ports:
        - containerPort: 8000
        volumeMounts:
          {{- if $v.mountPath }}
        - mountPath: {{ $v.mountPath }}
          readOnly: {{ $v.readonly }}
          name: xrootd-{{ $appname }}-fs
          {{- end }}
        - mountPath: /etc/grid-security/xrootdcert.pem
          name: xrootd-{{ $appname }}-cert
          subPath: xrootdcert.pem
        - mountPath: /etc/grid-security/xrootdkey.pem
          name: xrootd-{{ $appname }}-key
          subPath: xrootdkey.pem
        - mountPath: /tmp/macaroon-secret
          name: xrootd-{{ $appname }}-macaroon-secret
          subPath: macaroon-secret
        - mountPath: /opt/usergroups/
          name: usersgroups-{{ $appname }}
      dnsConfig: {{ $v.dnsConfig | default $.Values.default_params.dnsConfig | toJson }}
      dnsPolicy: None
      {{- if  $v.nodeSelector }}
      nodeSelector:
        kubernetes.io/hostname: {{ $v.nodeSelector }}
      {{- end }}
      restartPolicy: Always
      volumes:
      {{- if $v.mountPath }}
      - hostPath:
          path: {{ $v.mountPath }}
        name: xrootd-{{ $appname }}-fs
      {{- end }}
      - name: xrootd-{{ $appname }}-cert
        secret:
          defaultMode: 420
          items:
          - key: tls.crt
            path: xrootdcert.pem
          secretName: incommon-v2-{{ $k }}
      - name: xrootd-{{ $appname }}-key
        secret:
          defaultMode: 384
          items:
          - key: tls.key
            path: xrootdkey.pem
          secretName: incommon-v2-{{ $k }}
      - name: xrootd-{{ $appname }}-macaroon-secret
        secret:
          defaultMode: 420
          items:
          - key: macaroon-secret
            path: macaroon-secret
          secretName: xrootd-{{ $appname }}-secrets
      - name: usersgroups-{{ $appname }}
        configMap:
          name: usersgroups

{{- end }}
