{{- range $k, $v := .Values.origins }}
  {{- $appname := $k | splitList "." | first | trunc 40 | trimSuffix "-" }}
---
apiVersion: v1
data:
  macaroon-secret: {{ ($v.macaroon_secret) | default $.Values.default_params.macaroon_secret | b64enc | quote }}
kind: Secret
metadata:
  name: xrootd-{{ $appname }}-secrets
  namespace: {{ $.Values.namespace }}
{{- end }}
