{{- range $key, $value := .Values.services }}
apiVersion: v1
data:
  macaroon-secret: {{ $value.macaroon_secret }}
kind: Secret
metadata:
  name: {{ $key }}-secrets
  namespace: sense
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $key }}
  namespace: sense  # The namespace where the secret will be stored
spec:
  # Secret names are always required.
  secretName: incommon-v2-{{ $value.hostname }}  # The Secret name that Contains the certificate
  commonName: {{ $value.hostname }} # The certificate domain name
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  dnsNames:
    - {{ $value.hostname }}
  # Issuer references are always required.
  issuerRef:
    name: incommon-v2-prod  # The name of an Issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xrootd-{{ $key }}
  namespace: sense
  labels:
    io.kompose.service: xrootd-{{ $key }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: xrootd-{{ $key }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: xrootd-{{ $key }}
      annotations:
        k8s.v1.cni.cncf.io/networks:
            '[{
  {{- if $value.network.name }}
                    "name": "{{ $value.network.name }}",
  {{- end -}}
  {{- if $value.network.ips }}
                    "ips": {{ $value.network.ips }},
  {{- end -}}
  {{- if $value.network.mac }}
                    "mac": "{{ $value.network.mac }}",
  {{- end -}}
  {{- if $value.network.gateway }}
                    "gateway": {{ $value.network.gateway }}
  {{- end }}
            }]'
    spec:
      containers:
        - image: sdnsense/xrootd-stageout-server:latest
          imagePullPolicy: Always
{{- if $value.env }}
          env:
  {{- range $envvar := $value.env }}
          - name: {{ $envvar.name }}
            value: {{ $envvar.value }}
  {{- end }}
{{- end }}
          lifecycle:
            postStart:
              exec:
                command:
                - "/bin/sh"
                - "-c"
                -  >
                  mkdir /etc/grid-security/xrootd/;
                  cp /etc/grid-security/xrootd*.pem /etc/grid-security/xrootd/;
                  chown -R xrootd:xrootd /etc/grid-security/xrootd/;
                  cp /tmp/macaroon-secret /etc/xrootd/macaroon-secret;
                  chown xrootd:xrootd /etc/xrootd/macaroon-secret;
                  mkdir -p /storage/cms/store/{data,mc,user,temp};
                  mkdir -p /storage/cms/store/user/jbalcas;
                  chown -R cmsuser:cmsuser /storage/cms/store;
                  chown -R jbalcas:jbalcas /storage/cms/store/user/jbalcas;
          name: xrootd-{{ $key }}
          securityContext:
            capabilities:
              add:
                - CAP_SETUID
                - CAP_SETGID
                - CAP_DAC_OVERRIDE
          resources:
            limits:
              cpu: 16
              memory: 16Gi
            requests:
              cpu: 4
              memory: 8Gi
          volumeMounts:
          - mountPath: /etc/passwd
            name: xrootd-{{ $key }}-passwd
            readOnly: true
          - mountPath: /etc/group
            name: xrootd-{{ $key }}-group
            readOnly: true
          - mountPath: /storage/cms
            name: xrootd-{{ $key }}-fs
          - mountPath: /etc/grid-security/xrootdcert.pem
            name: xrootd-{{ $key }}-cert
            subPath: xrootdcert.pem
          - mountPath: /etc/grid-security/xrootdkey.pem
            name: xrootd-{{ $key }}-key
            subPath: xrootdkey.pem
          - mountPath: /tmp/macaroon-secret
            name: xrootd-{{ $key }}-macaroon-secret
            subPath: macaroon-secret
      nodeSelector:
          kubernetes.io/hostname: {{ $value.nodeSelector }}
      restartPolicy: Always
      volumes:
        - name: xrootd-{{ $key }}-passwd
          hostPath:
            path: /etc/passwd
        - name: xrootd-{{ $key }}-group
          hostPath:
            path: /etc/group
        - name: xrootd-{{ $key }}-fs
          hostPath:
            path: /mnt/raid0
        #- name: xrootd-{{ $key }}-fs
        #  emptyDir:
        #    medium: Memory
        #    sizeLimit: 41Gi
        #- name: xrootd-{{ $key }}-fs
        #  persistentVolumeClaim:
        #    claimName: cephfs-pvc
        #    readOnly: false
        - name: xrootd-{{ $key }}-cert
          secret:
            secretName: incommon-v2-{{ $value.hostname }}
            items:
            - key: tls.crt
              path: xrootdcert.pem
            defaultMode: 0644
        - name: xrootd-{{ $key }}-key
          secret:
            secretName: incommon-v2-{{ $value.hostname }}
            items:
            - key: tls.key
              path: xrootdkey.pem
            defaultMode: 0600
        - name: xrootd-{{ $key }}-macaroon-secret
          secret:
            secretName: xrootd-{{ $key }}-secrets
            items:
            - key: macaroon-secret
              path: macaroon-secret
            defaultMode: 0644
status: {}
{{- end }}
